---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: skj03/python-mysql:3
          ports:
            - containerPort: 5000
          env:
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: db_password
            - name: db_name
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: db_name
            - name: db_user
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: db_user

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapp
  type: LoadBalancer